### ISSUE TITLE
$PATH with different build configurations

### ISSUE THREAD

**Issue by icui** [PrincetonUniversity/SPECFEMPP#151]
Right now a single specfem2d path doesn't work well when users need to run specfem with multiple build configurations e.g. with and without GPU. A few possible solutions:

- Reconsider the recommendation that specfem2d needs to be in the PATH
- Allow multiple build targets and make the specfem2d in PATH a script that chooses the target to use e.g. ```specfem2d -b cpu``` and ```specfem2d -b gpu```
- Use a unified binary for multiple build configurations and determine the config at run time.

**Comment by Rohit-Kakodkar** [comment]
In terms of the 3rd case I think Kokkos doesnt would allow you to build same target for different architures. The only way of doing this would be to have a CPU driver and GPU driver - requiring significant code changes.

**Comment by Rohit-Kakodkar** [comment]
We can remove the recommendation for adding SPECFEM to $PATH. Maybe we should wait to see if this is actually an issue. I am not sure how many people would actually use different targets within the same workflow :|
