### ISSUE TITLE
Add test to check whether the properties are correctly assigned.

### ISSUE THREAD

**Issue by lsawade** [PrincetonUniversity/SPECFEMPP#264]
Add a unit-tests, that checks whether `specfem::materials::properties` has been read correctly. 

This can be adapted to other "test" meshes

**Comment by Rohit-Kakodkar** [comment]
I think these tests should go in `tests/unit-tests/mesh`. Right now that only implements if meshes were read (doesn't matter if it was read correctly or not). I can format `tests/unit-tests/mesh` and check if things were read correctly.

**Comment by lsawade** [comment]
Oh I was about to start on this, when I saw your assignment!
