### ISSUE TITLE
Implement a generic way of printing enum types

### ISSUE THREAD

**Issue by lsawade** [PrincetonUniversity/SPECFEMPP#266]
Not a problem, but for testing and error clarity it would be great to be able to print the enum types, without invoking the debugger.

Operator overloading works. Something like this 

```cpp

enum specfem::element::medium_tag
{
    elastic, acoustic
};

std::ostream& operator<<(std::ostream& os, const TokenType Token)
{
  switch(medium_tag)
  {
    case specfem::element::medium_tag::elastic:
      os << "MediumTag: Elastic";
      break;
    case specfem::element::medium_tag::acoustic:
      os << "MediumTag: Acoustic";
      break;
    default:
      os << "MediumTag: Unknown";
      break;
  }
  return os;
}
```

but the problem is that we cannot access tag that have not been defined for example.

For the unit tests this could be very powerful.

**Comment by Rohit-Kakodkar** [comment]
I think you want to do reflection. Its not part of the standard yet.  We could do something with macros easily but its not clean. 

This Chat output suggests some macro ways. I also like the magic_enum approach since its an easy dependecy to install. 
https://chatgpt.com/share/67586972-e668-8009-8fb0-958b6f880d8c

**Comment by lsawade** [comment]
I want to do reflection, indeed. I do not like the map option because we would need to rewrite something for each enum type; same with stringview in C+20. The macro seems elegant, and does not require a separate dependency.

**Comment by Rohit-Kakodkar** [comment]
I am okay with a Macro. we can always make this more elegant when reflection gets added in C++26

**Comment by lsawade** [comment]
This seems hard. 

Maybe you have an idea. I have been trying for a bit even asked copilot and co. but there seems to be no elegant way of handling variable arguments (`__VA_ARGS__`):

```cpp
#include <iostream>
#include <string>

#define ENUM_TO_STRING(name, ...) \
    enum class name { __VA_ARGS__ }; \
    const char* name##Strings[] = { #__VA_ARGS__ }; \
    inline const char* toString(name value) { \
        return name##Strings[static_cast<int>(value)]; \
    }

ENUM_TO_STRING(Color, Red, Green, Blue)

int main() {
    Color red = Color::Red;
    Color green = Color::G;
    Color blue = Color::G;
    std::cout << toString(red) << std::endl;
    std::cout << toString(green) << std::endl;
    std::cout << toString(blue) << std::endl;
    return 0;
}
```

will output.

```
Red, Green, Blue
Segmentation Fault
```

**Comment by Rohit-Kakodkar** [comment]
> This seems hard.
> 
> Maybe you have an idea. I have been trying for a bit even asked copilot and co. but there seems to be no elegant way of handling variable arguments (`__VA_ARGS__`):
> 
> ```c++
> #include <iostream>
> #include <string>
> 
> #define ENUM_TO_STRING(name, ...) \
>     enum class name { __VA_ARGS__ }; \
>     const char* name##Strings[] = { #__VA_ARGS__ }; \
>     inline const char* toString(name value) { \
>         return name##Strings[static_cast<int>(value)]; \
>     }
> 
> ENUM_TO_STRING(Color, Red, Green, Blue)
> 
> int main() {
>     Color red = Color::Red;
>     Color green = Color::Green;
>     Color blue = Color::Blue;
>     std::cout << toString(red) << std::endl;
>     std::cout << toString(green) << std::endl;
>     std::cout << toString(blue) << std::endl;
>     return 0;
> }
> ```
> 
> will output.
> 
> ```
> Red, Green, Blue
> Segmentation Fault
> ```

How did you get that segfault? https://www.programiz.com/online-compiler/0RZS3uRp1CTMX

**Comment by lsawade** [comment]
It's weird that you don't. 
```cpp
name##Strings[] = { #__VA_ARGS__ };
```
actually becomes
```cpp
const char* ColorStrings[] = { 'Red, Green, Blue' };
```
which is why the first output (`toString(red)`) prints 
```
Red, Green, Blue
```
since you are printing `ColorStrings[0]`. The following accesses should give segfaults;
```
ColorStrings[static_cast<int>(Color::Green)]
// ==
ColorStrings[1]
```
and
```
ColorStrings[static_cast<int>(Color::Blue)]
// ==
ColorStrings[2]
```
Of which neither exists. Hence, Segfault

**Comment by lsawade** [comment]
Ok, I got it. But it was a pain in the booty (not from hot pot).

```
#include <array>
#include <string_view>
#include <string>

// Helper macros to count arguments in __VA_ARGS__
#define COUNT_ARGS(...) COUNT_ARGS_IMPL(__VA_ARGS__, RSEQ_N())
#define COUNT_ARGS_IMPL(...) COUNT_ARGS_N(__VA_ARGS__)
#define COUNT_ARGS_N(                                             \
    _1, _2, _3, _4, _5, _6, _7, _8, _9, _10,                      \
    _11, _12, _13, _14, _15, _16, _17, _18, _19, _20,             \
    _21, _22, _23, _24, _25, _26, _27, _28, _29, _30,             \
    _31, _32, _33, _34, _35, _36, _37, _38, _39, _40,             \
    _41, _42, _43, _44, _45, _46, _47, _48, _49, _50,             \
    _51, _52, _53, _54, _55, _56, _57, _58, _59, _60,             \
    _61, _62, _63, N, ...) N
#define RSEQ_N()                                                  \
    63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,       \
    49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36,       \
    35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,       \
    21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7,      \
    6, 5, 4, 3, 2, 1, 0

// Helper macros for stringifying arguments
#define XSTRINGIFY(s) #s

// Define the STRINGARRAY<N> macros
#define STRINGARRAY1(s0) { XSTRINGIFY(s0) }
#define STRINGARRAY2(s0, s1) { XSTRINGIFY(s0), XSTRINGIFY(s1) }
#define STRINGARRAY3(s0, s1, s2) { XSTRINGIFY(s0), XSTRINGIFY(s1), XSTRINGIFY(s2) }
#define STRINGARRAY4(s0, s1, s2, s3) { XSTRINGIFY(s0), XSTRINGIFY(s1), XSTRINGIFY(s2), XSTRINGIFY(s3) }
// Add more STRINGARRAY<N> macros as needed...

// Macro dispatching using COUNT_ARGS to select the correct STRINGARRAY<N>
// !!! The nested dispatch is key !!! otherwise counts is not being evaluated
// and generating STRINGARRAY##COUNT_ARGS(__VA_ARGS__)(__VA_ARGS__), which does
// not make sense
#define STRINGARRAY_DISPATCH(count, ...) STRINGARRAY_(count, __VA_ARGS__)
#define STRINGARRAY_(count, ...) STRINGARRAY##count(__VA_ARGS__)
#define STRINGARRAY(...) STRINGARRAY_DISPATCH(COUNT_ARGS(__VA_ARGS__), __VA_ARGS__)

// Test ENUM_TO_STRING_ARRAY macro
#define ENUM_TO_STRING_ARRAY(enum_name, ...)                        \
    enum class enum_name { __VA_ARGS__ };                           \
    constexpr std::array<const char*, COUNT_ARGS(__VA_ARGS__)> enum_name##Strings = STRINGARRAY(__VA_ARGS__); \
    std::ostream& operator<<(std::ostream& os, enum_name e) {        \
        return os << std::string(enum_name##Strings[static_cast<int>(e)]);        \
    }

// Example usage
ENUM_TO_STRING_ARRAY(Color, Red, Green, Blue);

#include <iostream>
int main() {
    Color c = Color::Green;
    std::cout << "Color: " << c << std::endl;
    return 0;
}
```

**Comment by lsawade** [comment]
Closing this as we are using ::toString
