### ISSUE TITLE
Create `include/medium/elastic_anisotropic2d/elastic_anisotropic2d.hpp`

### ISSUE THREAD

**Issue by lsawade** [PrincetonUniversity/SPECFEMPP#270]

**Comment by Rohit-Kakodkar** [comment]
I believe the only function being used from that header is `impl_mass_matrix_component`. `impl_compute_stress_integrands` has moved to `specfem::medium` namespace. Feel free to move `impl_mass_matrix_component` to `specfem::medium` namespace if it isnt a lot of refactor.

**Comment by lsawade** [comment]
> I believe the only function being used from that header is `impl_mass_matrix_component`. `impl_compute_stress_integrands` has moved to `specfem::medium` namespace. Feel free to move `impl_mass_matrix_component` to `specfem::medium` namespace if it isnt a lot of refactor.

I'm not following, `impl_mass_matrix_component` is not in `include/medium/elastic_anisotropic2d/elastic_anisotropic2d.hpp`. Do you mean move `domain/impl/element/elastic/elastic2d.hpp:specfem::domain::impl::elements::impl_mass_matrix_component` to `include/medium/elastic_anisotropic2d/elastic_anisotropic2d.hpp`?

**Comment by Rohit-Kakodkar** [comment]
My bad I thought you were working on the `mass_matrix` file and not the `medium` file. But yes we need to move `impl::element::impl_mass_matrix_component` to `medium` namespace. I have a task for the same within the refactor section

**Comment by lsawade** [comment]
closed by #271
